Merkle Memberships Program; Clean up
mlabs-haskell/MinAuth pull request #2
Opened 2023-09-20 11:30 UTC by chfanghr

2023-10-02 21:52 UTC, adamczykm requested changes

2023-10-02 21:52 UTC, adamczykm commented on src/library/plugin/pluginType.ts
> +export interface IMinAuthPlugin<FetchPublicInput, Output> {
Just a rename

2023-10-02 21:52 UTC, adamczykm commented on src/library/tools/pluginServer/config.ts
> +import { MemberSetPlugin } from "./plugins/passwordTree/server";
Just a rename

2023-10-02 21:52 UTC, adamczykm commented on src/library/tools/pluginServer/index.ts
> +import { IMinAuthPlugin } from '../../../library/plugin/pluginType';
The previous path has not been working for me.

2023-10-02 21:52 UTC, adamczykm commented on src/plugins/passwordTree/common/passwordTreeProgram.ts
> +// Prove knowledge of a preimage of a hash in a merkle tree.
The zk program has changed. The other one was not doing any meaningful ZK operation. This one hides the user. 
The rest of the code needs fixing now.

2023-10-02 21:55 UTC, adamczykm commented
Additionally, I think that we will need to rethink the IProver interface. Good that we don't use it anywhere yet.

2023-10-03 12:32 UTC, adamczykm commented on src/plugins/passwordTree/common/passwordTreeProgram.ts
> +                    .calculateRoot(Poseidon.hash([publicInput.root]))
MISTAKE: use preimage

2023-10-03 12:33 UTC, adamczykm commented on src/plugins/passwordTree/common/passwordTreeProgram.ts
> +                    { recursiveMekleRootHash: Poseidon.hash([publicInput.root, earlierProof.publicOutput.recursiveMekleRootHash]) });
rename to recursive hash

2023-10-03 12:33 UTC, adamczykm commented on src/plugins/passwordTree/common/passwordTreeProgram.ts
> +                    .calculateRoot(Poseidon.hash([publicInput.root]))
Mistake: use preimage instead

2023-10-03 12:34 UTC, adamczykm commented on src/plugins/passwordTree/common/passwordTreeProgram.ts
> +export const ProvePasswordInTreeProgram = Experimental.ZkProgram({
rename to e.g MerkleMemberships program

2023-10-03 12:35 UTC, adamczykm commented on src/plugins/passwordTree/common/passwordTreeProgram.ts
> +    preImage: Field
rename to "secret"

2023-10-06 13:56 UTC, adamczykm commented on src/plugins/merkleMemberships/client/index.ts
It's a nice functional implementation but got noisy. Typescript syntax is not very beautiful it appears. I'll propose some changes.

2023-10-06 14:08 UTC, adamczykm commented on src/plugins/merkleMemberships/common/merkleMembershipsProgram.ts
> +export class MerkleMembershipTreeWitness extends
These are too wordy...

2023-10-06 15:10 UTC, adamczykm requested changes
There are some changes required.
Please try to add some docstrings already. They don't have to be beautiful yet, but should explain the high-level operations of the code. To make it easier to understand how the proof is achieved etc. 
Additionaly, we need the headless client to be able to test the flow of the updated plugin. 
It can be done with another PR though.

2023-10-06 15:10 UTC, adamczykm commented on src/plugins/merkleMemberships/server/index.ts
> +export type MerkleMembershipsPublicInputArgs =
Wordiness again. Maybe we can drop the "MarkleMembership" prefix.

2023-10-06 15:10 UTC, adamczykm commented on src/plugins/merkleMemberships/server/index.ts
> +  async verifyAndGetOutput(
The proof is not being verified.
Please add the proof verification and code docstring that would explain what is going on.

2023-10-06 15:10 UTC, adamczykm commented on src/plugins/merkleMemberships/server/index.ts
> +  async verifyAndGetOutput(
Rename `publicInputArgs` to `merkleRoots`.
Also, the argument is not an index of a tree it is its root.
The trees should be stored by the root hash and not the index.

2023-10-06 15:10 UTC, adamczykm commented on tsconfig.json
> -      "*": [ "src/*", "src/library/*" ]
let's add an alias for the library directory so that instead of ../.../../../../[path] we can write @lib/[path]

2023-10-09 10:00 UTC, chfanghr commented on src/plugins/merkleMemberships/server/index.ts
> +  async verifyAndGetOutput(
> The proof is not being verified.

How so? The proof has already been verified by the server before entering this function. See https://github.com/mlabs-haskell/MinAuth/pull/7/files#diff-0b5d80d7710738d6c4dc8de490d335c59ba29ade54dd75b2027b3b3513c7452dR35-R69

2023-10-10 00:20 UTC, adamczykm requested changes
The leaf index problem is still unresolved. The server should be sending the entire tree or all the leaves to ensure anonimity.

2023-10-10 00:20 UTC, adamczykm commented on src/library/tools/pluginServer/index.ts
>        // Step 1: check that the proof was generated using a certain verification key.
This does not only verify that the proof was generated using the verification key and even if it does the gist is that it verifies that the proof is valid - it does not exit on broken assertions,  against some compiled source program. 
So maybe let's say:
```
// Step 1: check that the proof is valid against the given verification key.
```

2023-10-10 00:20 UTC, adamczykm commented on src/plugins/merkleMemberships/client/index.ts
> +    const proof: O.Option<ZkProof> = await A.reduce(
Add a comment here please. Something akin to:
```
// For each pair of inputs (secret and public) add another layer of the recursive proof

2023-10-10 00:20 UTC, adamczykm commented on src/plugins/merkleMemberships/client/index.ts
> +  async fetchPublicInputs(
The problem here is that asking for a specific index of the tree reveals the identity.
The only solution is to transfer the entire tree. Then it should be searched for the index and this way the witness could be generated.
If there's no easy way to serialize the tree then the list of all leaves should be send and the tree should be rebuilt.

2023-10-10 00:20 UTC, adamczykm commented on src/plugins/merkleMemberships/server/index.ts
> +    '/getWitness/:treeRoot/:leafIndex': async (req, resp) => {
ditto:
the leafindex can be passsed to the server.

2023-10-10 15:41 UTC, chfanghr commented on src/plugins/merkleMemberships/client/index.ts
> +  async fetchPublicInputs(
This is apparently not very efficient. I don't see why this hurts anonymity - a client can always make a bunch of junk requests to confuse the server if the server decides to log the traffic. 

Aside from that, I have some concerns regarding the security of this implementation - if someone knows the value x where `Poseidon.hash([x]) == Field(0)` and if any of the trees have one or more holes, we are screwed.

2023-10-13 13:21 UTC, adamczykm approved these changes
Approving before the deeper review.

2023-10-13 13:21 UTC, merged